apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:16
          command: ["sh","-c","until pg_isready -h payment-db -p 5432; do sleep 2; done"]
      containers:
        - name: payment-service
          image: innowisepractical-payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://payment-db:5432/paymentsidb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: USER_SERVICE_BASE_URL
              value: http://user-service:8082
            - name: ORDER_SERVICE_BASE_URL
              value: http://order-service:8083
            - name: API_BASE_URL
              value: https://www.randomnumberapi.com
            - name: API_PATH
              value: /api/v1.0/random
            - name: API_QUERY
              value: ?min=1&max=100&count=1

          startupProbe:
            httpGet:
              path: /actuator/health/startup
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 90
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 8084
