apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - until nc -z order-db 5432; do echo waiting for order-db; sleep 2; done;
        - name: wait-for-user-service
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for user-service..."
              timeout 60 sh -c 'until nc -z user-service 8082; do echo waiting for user-service; sleep 2; done'

      containers:
        - name: order-service
          image: innowisepractical-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://order-db:5432/orderidb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: USER_SERVICE_BASE_URL
              value: http://user-service:8082
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 60

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8083
      targetPort: 8083