apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-services'
        static_configs:
          - targets: [ 'auth-service:8081', 'user-service:8082', 'order-service:8-83', 'payment-service:8084' ]
