apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:16
          command:
            - sh
            - -c
            - |
              until pg_isready -h user-db -p 5432; do
                echo "waiting for user-db";
                sleep 2;
              done
      containers:
        - name: user-service
          image: innowisepractical-user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://user-db:5432/useridb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          #livenessProbe:
            #httpGet:
              #path: /actuator/health/liveness
              #port: 8082
            #initialDelaySeconds: 40
            #periodSeconds: 10
          #readinessProbe:
            #httpGet:
              #path: /actuator/health/readiness
              #port: 8082
           #initialDelaySeconds: 40
            #periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8082
      targetPort: 8082